# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

whichLowerEQThanX <- function(x, y) {
    .Call('_HistDAWass_whichLowerEQThanX', PACKAGE = 'HistDAWass', x, y)
}

COMP_Q_VECT <- function(x, p, vp) {
    .Call('_HistDAWass_COMP_Q_VECT', PACKAGE = 'HistDAWass', x, p, vp)
}

concatenate_and_sort <- function(a, b) {
    .Call('_HistDAWass_concatenate_and_sort', PACKAGE = 'HistDAWass', a, b)
}

REGISTER2 <- function(a, b) {
    .Call('_HistDAWass_REGISTER2', PACKAGE = 'HistDAWass', a, b)
}

PREPARE_A_VEC_MAT <- function(MAT) {
    .Call('_HistDAWass_PREPARE_A_VEC_MAT', PACKAGE = 'HistDAWass', MAT)
}

MEDIA_V <- function(MAT, wei) {
    .Call('_HistDAWass_MEDIA_V', PACKAGE = 'HistDAWass', MAT, wei)
}

SSQ_RCPP <- function(MAT, wei) {
    .Call('_HistDAWass_SSQ_RCPP', PACKAGE = 'HistDAWass', MAT, wei)
}

COV_RCPP <- function(MAT, wei) {
    .Call('_HistDAWass_COV_RCPP', PACKAGE = 'HistDAWass', MAT, wei)
}

CORR_RCPP <- function(MAT, wei) {
    .Call('_HistDAWass_CORR_RCPP', PACKAGE = 'HistDAWass', MAT, wei)
}

M_STD_H <- function(o) {
    .Call('_HistDAWass_M_STD_H', PACKAGE = 'HistDAWass', o)
}

